# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1afyw8pl805yw639l8frfd4qmrsppixdr20mjcdapprdjv5ia4m8";
    aarch64-linux = "1iv7mclmrvxc5zm9qgjs4s88vz67xjrq1jyddhddq4rk96jsrd21";
    x86_64-darwin = "1hgbqxip1qdkhfkijfbr1visd195dh4gmm23qps2ig2fnrhzw0ri";
    aarch64-darwin = "06cq4bryjqjfqlc7fkx4ggnrhqzs698crzdvkyplvhjpgv787fvb";
  };

  urlMap = {
    x86_64-linux = "https://github.com/rwilgaard/xcv/releases/download/v0.5.0/xcv_0.5.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/rwilgaard/xcv/releases/download/v0.5.0/xcv_0.5.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/rwilgaard/xcv/releases/download/v0.5.0/xcv_0.5.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/rwilgaard/xcv/releases/download/v0.5.0/xcv_0.5.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "xcv";
  version = "0.5.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./xcv $out/bin/xcv
    runHook postInstall
  '';
  postInstall = ''
    installShellCompletion --cmd xcv \
    --zsh <($out/bin/xcv completion zsh) \
    --bash <($out/bin/xcv completion bash) \
    --fish <($out/bin/xcv completion fish)
  '';

  meta = {
    description = "CLI tool for inspecting, validating, and comparing X.509 certificate chains";
    homepage = "https://github.com/rwilgaard/xcv";
    license = lib.licenses.mit;
    mainProgram = "xcv";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
