# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1ak90l7krjpjzkk8b00yjbm5gvj1r3qfr8hkx5jdazkyv7msyyw0";
    aarch64-linux = "0hf0z1hj96l9cj23hbshanxklafm7j30169f8xq8x428hmkf8f8m";
    x86_64-darwin = "0lj51mzw9fmki6793m9n6aka2lvnj6xlh6prxhmfl7pn6vvw0gmq";
    aarch64-darwin = "11clbrvchb88d04av1vvq0vkg0iy4qyqdv6nrwrnihrfzv7bgscr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/rwilgaard/xcv/releases/download/v0.6.0/xcv_0.6.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/rwilgaard/xcv/releases/download/v0.6.0/xcv_0.6.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/rwilgaard/xcv/releases/download/v0.6.0/xcv_0.6.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/rwilgaard/xcv/releases/download/v0.6.0/xcv_0.6.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "xcv";
  version = "0.6.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./xcv $out/bin/xcv
    runHook postInstall
  '';
  postInstall = ''
    installShellCompletion --cmd xcv \
    --zsh <($out/bin/xcv completion zsh) \
    --bash <($out/bin/xcv completion bash) \
    --fish <($out/bin/xcv completion fish)
  '';

  meta = {
    description = "CLI tool for inspecting, validating, and comparing X.509 certificate chains";
    homepage = "https://github.com/rwilgaard/xcv";
    license = lib.licenses.mit;
    mainProgram = "xcv";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
