# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
  installShellFiles,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1vxfncqcaq175i380xjb0mbl39r2lgziby3003cvpdwnjp9fcir2";
    aarch64-linux = "1gi1l1mq3aq346kh1bk6nfa447axjwsxiap3qx4ffgpxfsin9krh";
    x86_64-darwin = "0ak1li28jy5c9y1snixzhlfbp0mcq7pdcwvyj2k29mmar33ksmr3";
    aarch64-darwin = "099ig5w7lsfn07zs8fms7f8lgfb9vw8gmcz8p86hih0rigrqcdph";
  };

  urlMap = {
    x86_64-linux = "https://github.com/rwilgaard/xcv/releases/download/v0.3.0/xcv_0.3.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/rwilgaard/xcv/releases/download/v0.3.0/xcv_0.3.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/rwilgaard/xcv/releases/download/v0.3.0/xcv_0.3.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/rwilgaard/xcv/releases/download/v0.3.0/xcv_0.3.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "xcv";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./xcv $out/bin/xcv
    wrapProgram $out/bin/xcv --prefix PATH : ${lib.makeBinPath ([ installShellFiles ])}
  '';
  postInstall = ''
    installShellCompletion --cmd xcv \
    --zsh <($out/bin/xcv completion zsh) \
    --bash <($out/bin/xcv completion bash) \
    --fish <($out/bin/xcv completion fish)
  '';

  meta = {
    description = "CLI tool for inspecting, validating, and comparing X.509 certificate chains";
    homepage = "https://github.com/rwilgaard/xcv";
    license = lib.licenses.mit;
    mainProgram = "xcv";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
