# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1v9ib30c5lpkg55c4wwss4ypa4iax3q52r7dw6bsaqvw6w6q6wyf";
    aarch64-linux = "0qsmankjfaqfpzilsa4cwlhb4xn95wclj3v05asklv0wv2mfbnzz";
    x86_64-darwin = "1yf4i78bg0zkj46zqd8czqmhknqqysl5dljg8hf6c62ym35bppjh";
    aarch64-darwin = "08yjb0rz0a2pi0wwkmw0ipish0v0ynsyk5q279jgng8ng6ys0fpd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/rwilgaard/thop/releases/download/v0.7.0/thop_0.7.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/rwilgaard/thop/releases/download/v0.7.0/thop_0.7.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/rwilgaard/thop/releases/download/v0.7.0/thop_0.7.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/rwilgaard/thop/releases/download/v0.7.0/thop_0.7.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "thop";
  version = "0.7.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./thop $out/bin/thop
  '';

  meta = {
    description = "Fuzzy tmux session manager with frecency ranking";
    homepage = "https://github.com/rwilgaard/thop";
    license = lib.licenses.mit;
    mainProgram = "thop";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
