# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1mz000k9jhb0bmvl236i0x3ld56cl0iqypiaw7xm4l5n9p5jbpzj";
    aarch64-linux = "1q6plllxbnd4k2q86r38hdac7cd5i22wy51j3gbpr8yiqc2klpb4";
    x86_64-darwin = "06h0bl50mzhg3qbblprbfxirgpsgcl91q5pszr20v7ck6vjs1vnp";
    aarch64-darwin = "0x39v24vajz7a9pdjy57khzl0s9yj84rp0yzday9620yf2swwfs5";
  };

  urlMap = {
    x86_64-linux = "https://github.com/rwilgaard/thop/releases/download/v0.8.0/thop_0.8.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/rwilgaard/thop/releases/download/v0.8.0/thop_0.8.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/rwilgaard/thop/releases/download/v0.8.0/thop_0.8.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/rwilgaard/thop/releases/download/v0.8.0/thop_0.8.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "thop";
  version = "0.8.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./thop $out/bin/thop
  '';

  meta = {
    description = "Fuzzy tmux session manager with frecency ranking";
    homepage = "https://github.com/rwilgaard/thop";
    license = lib.licenses.mit;
    mainProgram = "thop";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
