# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1q1cn3xc96ar7ris0h6g7h2zmja4gxf14g5by3bn54nwc92f19yz";
    aarch64-linux = "1jsmmn1f8pvxyw4zgg44zqfi70x33nd38fd9x8c2k0zkfmqi3k8m";
    x86_64-darwin = "19flzj4yxr2al6z9d1d5a258rs8qkh1755yk61yk6a6cxx2apv24";
    aarch64-darwin = "07y3byn777bhk6hh07jj4bng2aa26hhx3w0fwnvyajbdzra8jg1v";
  };

  urlMap = {
    x86_64-linux = "https://github.com/rwilgaard/thop/releases/download/v0.5.0/thop_0.5.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/rwilgaard/thop/releases/download/v0.5.0/thop_0.5.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/rwilgaard/thop/releases/download/v0.5.0/thop_0.5.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/rwilgaard/thop/releases/download/v0.5.0/thop_0.5.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "thop";
  version = "0.5.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./thop $out/bin/thop
  '';

  meta = {
    description = "Fuzzy tmux session manager with frecency ranking";
    homepage = "https://github.com/rwilgaard/thop";
    license = lib.licenses.mit;
    mainProgram = "thop";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
